package com.carserviceapp.model;

import java.util.Objects;

/**
 * Abstract base class for employees.
 */
public abstract class Employee extends AbstractPerson {
    protected String employeeId;
    protected double salary;

    public Employee(String idPrefix, String firstName, String lastName, String email, String phone, double salary) {
        super(idPrefix, firstName, lastName, email, phone);
        this.employeeId = this.id; // Use same ID as generated by AbstractPerson
        this.salary = salary;
    }

    public String getEmployeeId() {
        return employeeId;
    }

    // No setter for employeeId as it's typically assigned once

    public double getSalary() {
        return salary;
    }

    public void setSalary(double salary) {
        this.salary = salary;
    }

    @Override
    public String getDisplayInfo() {
        return "Employee ID: " + id + ", Name: " + firstName + " " + lastName + ", Email: " + email + ", Phone: " + phone + ", Salary: $" + salary;
    }

    @Override
    public String toString() {
        return getDisplayInfo();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        Employee employee = (Employee) o;
        return Objects.equals(employeeId, employee.employeeId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), employeeId);
    }
}